// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://demweczdrbhexqknqcoj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRlbXdlY3pkcmJoZXhxa25xY29qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMDExMzEsImV4cCI6MjA3Mzc3NzEzMX0.kVoodG_oGHt2L9u72kubm2M67pQZlpXMY2E4O5Qb27g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});